services:

  localstack:
    image: localstack/localstack:2.3.2
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DOCKER_HOST=unix:///var/run/docker.sock

  api:
    build: ./api
    env_file:
      - .env
    depends_on:
      - localstack

  agent:
    build: ./agent
    ports:
      - "8080:8080"
    depends_on:
      - api

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - agent

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
    grafana_data:
    prometheus_data:
