events {}

http {
    server {
        listen 80;
        
        location /upload {
            proxy_pass http://api:8000/upload;
        }

        location /metrics {
            proxy_pass http://api:8000/metrics;
        }

        location /trigger {
            proxy_pass http://agent:8080/trigger;
        }
    }
}